### ISSUE TITLE
Error while building app

### ISSUE THREAD

**Issue by Lev-Guzeev** [mano-mykingdom/titanium-mupdf#1]
Hello! I've installed the module into my app, but it gives error when I'm trying to run the app:
[INFO] :   Generating i18n files
[INFO] :   Generating /Users/Hunite/Documents/Titanium_Studio_Workspace_BigCloud/MyApp/build/android/res/values/theme.xml
[INFO] :   Packaging application: /Users/Hunite/Library/android-sdk-macosx/build-tools/20.0.0/aapt "package" "-f" "-m" "-J" "/Users/Hunite/Documents/Titanium_Studio_Workspace_BigCloud/MyApp/build/android/gen" "-M" "/Users/Hunite/Documents/Titanium_Studio_Workspace_BigCloud/MyApp/build/android/AndroidManifest.xml" "-A" "/Users/Hunite/Documents/Titanium_Studio_Workspace_BigCloud/MyApp/build/android/bin/assets" "-S" "/Users/Hunite/Documents/Titanium_Studio_Workspace_BigCloud/MyApp/build/android/res" "-I" "/Users/Hunite/Library/android-sdk-macosx/platforms/android-15/android.jar" "-I" "/Users/Hunite/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/android/titanium.jar" "-I" "/Users/Hunite/Library/Application Support/Titanium/mobilesdk/osx/3.3.0.GA/android/aps-analytics.jar" "-F" "/Users/Hunite/Documents/Titanium_Studio_Workspace_BigCloud/MyApp/build/android/bin/app.ap_" "--auto-add-overlay" "--extra-packages" "ti.modules.titanium.ui:android.support.v7.appcompat" "-S" "/var/folders/7r/jqhffj1j2zs87dkf1_m56h9h0000gn/T/114825-53843-14k2quj/res" "-S" "/var/folders/7r/jqhffj1j2zs87dkf1_m56h9h0000gn/T/114825-53843-66adu7/res"
[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Failed to package application:
[ERROR] :  
[ERROR] :  ERROR: In <declare-styleable> TwoWayView, unable to find attribute android:textAlignment

What can I do with this?
Thanks in advance! :)

**Comment by mano-mykingdom** [comment]
This module is built with 3.4.0.GA. Seems you are compiling on a lower version.
