### ISSUE TITLE
NullPointerException - ReaderView

### ISSUE THREAD

**Issue by n0n1** [mano-mykingdom/titanium-mupdf#10]
Hello, I'm try launch titanium classic project with your module. But I get **NullPointerException**. 

I'm using ti sdk - 3.5.0.GA, 3.5.1.GA.
what to do?
You may do working example with your module?

-- Start application log -----------------------------------------------------
[INFO] :   TiApplication: (main) [0,0] checkpoint, app created.
[DEBUG] :  dalvikvm: GC_CONCURRENT freed 214K, 8% free 3069K/3332K, paused 0ms+8ms, total 12ms
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 247K, 12% free 3176K/3604K, paused 0ms, total 0ms
[DEBUG] :  dalvikvm: GC_CONCURRENT freed 188K, 6% free 3451K/3660K, paused 4ms+4ms, total 8ms
[DEBUG] :  dalvikvm: GC_CONCURRENT freed 297K, 4% free 3786K/3940K, paused 4ms+4ms, total 12ms
[INFO] :   TiApplication: (main) [64,64] Titanium 3.5.0 (2015/01/12 15:33 0014f83)
[DEBUG] :  dalvikvm: Trying to load lib /data/app-lib/com.pdf.view-2/libstlport_shared.so 0xa5027278
[INFO] :   TiApplication: (main) [16,80] Titanium Javascript runtime: v8
[DEBUG] :  dalvikvm: Added shared lib /data/app-lib/com.pdf.view-2/libstlport_shared.so 0xa5027278
[DEBUG] :  dalvikvm: No JNI_OnLoad found in /data/app-lib/com.pdf.view-2/libstlport_shared.so 0xa5027278, skipping init
[DEBUG] :  dalvikvm: Trying to load lib /data/app-lib/com.pdf.view-2/libkroll-v8.so 0xa5027278
[DEBUG] :  dalvikvm: Added shared lib /data/app-lib/com.pdf.view-2/libkroll-v8.so 0xa5027278
[DEBUG] :  MupdfModule: (main) [28,108] inside onAppCreate
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
[ERROR] :  E/        : UID 10058 asks for /proc/cpuinfo
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2neon
[ERROR] :  E/        : UID 10058 is not in ARM UID list files
[WARN] :   V8Object: (KrollRuntimeThread) [36,36] Runtime disposed, cannot set property 'userAgent'
[DEBUG] :  dalvikvm: Trying to load lib /data/app-lib/com.pdf.view-2/libcom.mykingdom.mupdf.so 0xa5027278
[DEBUG] :  dalvikvm: Added shared lib /data/app-lib/com.pdf.view-2/libcom.mykingdom.mupdf.so 0xa5027278
[DEBUG] :  dalvikvm: No JNI_OnLoad found in /data/app-lib/com.pdf.view-2/libcom.mykingdom.mupdf.so 0xa5027278, skipping init
[DEBUG] :  dalvikvm: GC_CONCURRENT freed 436K, 12% free 3739K/4220K, paused 4ms+4ms, total 20ms
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 15K, 12% free 3807K/4288K, paused 8ms, total 8ms
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 1K, 12% free 3873K/4356K, paused 4ms, total 4ms
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed <1K, 11% free 3942K/4424K, paused 8ms, total 8ms
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 3K, 11% free 4009K/4492K, paused 4ms, total 4ms
[INFO] :   >>EXISTS>>>true
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed <1K, 11% free 4076K/4560K, paused 0ms, total 0ms
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed <1K, 11% free 4143K/4628K, paused 4ms, total 4ms
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 1K, 11% free 4210K/4696K, paused 4ms, total 4ms
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 10K, 10% free 4289K/4764K, paused 0ms, total 0ms
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 5.386MB for 1209852-byte allocation
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 1K, 9% free 5469K/5948K, paused 4ms, total 4ms
[DEBUG] :  dalvikvm: GC_CONCURRENT freed <1K, 9% free 5469K/5948K, paused 4ms+0ms, total 8ms
[DEBUG] :  dalvikvm: Trying to load lib /data/app-lib/com.pdf.view-2/libtiverify.so 0xa5027278
[DEBUG] :  dalvikvm: Added shared lib /data/app-lib/com.pdf.view-2/libtiverify.so 0xa5027278
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = com.pdf.view.PdfviewActivity@52897600
[ERROR] :  E/        : UID 10058 asks for /proc/cpuinfo
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2neon
[ERROR] :  E/        : UID 10058 is not in ARM UID list files
[DEBUG] :  libEGL: loaded /system/lib/egl/libEGL_genymotion.so
[DEBUG] :  D/        : HostConnection::get() New Host Connection established 0xb933e128, tid 2012
[DEBUG] :  libEGL: loaded /system/lib/egl/libGLESv1_CM_genymotion.so
[DEBUG] :  libEGL: loaded /system/lib/egl/libGLESv2_genymotion.so
[WARN] :   EGL_genymotion: eglSurfaceAttrib not implemented
[ERROR] :  OpenGLRenderer: Getting MAX_TEXTURE_SIZE from GradienCache
[ERROR] :  OpenGLRenderer: MAX_TEXTURE_SIZE: 16384
[ERROR] :  OpenGLRenderer: Getting MAX_TEXTURE_SIZE from Caches::initConstraints()
[ERROR] :  OpenGLRenderer: MAX_TEXTURE_SIZE: 16384
[DEBUG] :  OpenGLRenderer: Enabling debug mode 0
[WARN] :   TiBaseFile: (KrollRuntimeThread) [412,412] Method is not supported org.appcelerator.titanium.io.TiResourceFile : getParent
[INFO] :   {"bubbleParent":true,"rect":{"height":0,"y":0,"x":0,"width":0},"children":[],"keepScreenOn":false,"size":{"height":0,"y":0,"width":0,"x":0},"visible":true,"apiName":"Ti.Proxy","backgroundRepeat":false,"enabled":true,"file":{"readonly":true,"bubbleParent":true,"writable":false,"directoryListing":[],"symbolicLink":false,"apiName":"Ti.Filesystem.File","hidden":false,"nativePath":"file:///android_asset/Resources/pdf/sample.pdf","executable":false,"size":24077155,"name":"/sample.pdf","parent":null}}
[INFO] :   COUNT PAGE ->0
[DEBUG] :  Window: Checkpoint: postWindowCreated()
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 138K, 6% free 5994K/6356K, paused 4ms, total 4ms
[ERROR] :  E/        : UID 10058 asks for /proc/cpuinfo
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2neon
[ERROR] :  E/        : UID 10058 is not in ARM UID list files
[WARN] :   EGL_genymotion: eglSurfaceAttrib not implemented
[DEBUG] :  AndroidRuntime: Shutting down VM
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4d5eb20)
[ERROR] :  TiApplication: (main) [1500,1912] Sending event: exception on thread: main msg:java.lang.NullPointerException; Titanium 3.5.0,2015/01/12 15:33,0014f83
[ERROR] :  TiApplication: java.lang.NullPointerException
[ERROR] :  TiApplication: 	at com.artifex.mupdflib.ReaderView.getOrCreateChild(ReaderView.java:843)
[ERROR] :  TiApplication: 	at com.artifex.mupdflib.ReaderView.onLayout(ReaderView.java:717)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14817)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14817)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14817)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14817)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14817)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14817)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14817)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
[ERROR] :  TiApplication: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doFrame(Choreographer.java:544)
[ERROR] :  TiApplication: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
[ERROR] :  TiApplication: 	at android.os.Handler.handleCallback(Handler.java:733)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:136)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5001)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)

**Comment by mano-mykingdom** [comment]
I had tested the sample with 3.5.1.GA, found it works. Also this module is being used in several other projects of mine. 

You may share the test case along with the PDF you used to test it. I can have a look.

**Comment by n0n1** [comment]
thanks! This is my [simple project ](https://drive.google.com/file/d/0Bx_p1PnPSl71MnU0QXhHMldqR3M/view?usp=sharing).

**Comment by mano-mykingdom** [comment]
@n0n1 Can you please upload the test case without the complied resource and build files?

**Comment by n0n1** [comment]
@mano-mykingdom sorry, I'm found my issue. 
I try load file from  -> Ti.Filesystem.resourcesDirectory	
``
var file = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "sample.pdf");
``
File is exist, but not exist  in module here:
<pre><code>
File file = fileProxy.getBaseFile().getNativeFile();
String path = file.getPath();
Log.d(TAG, path);
if (file.exists()) {
	Log.d(TAG, "PDF exists, trying to load");
	core = openFile(Uri.decode(Uri.fromFile(file).getEncodedPath()));
	mDocView.setAdapter(new MuPDFPageAdapter(getActivity(), this, core));
	pageCount = core.countPages();
	currentPage = 1;
} 
</code></pre>
file.exists() - false;

When I'm loading file to sdcard  - it's working.
``
var file = Ti.Filesystem.getFile(Ti.Filesystem.externalStorageDirectory, "sample.pdf");
``

Pls add message debug

``
if (file.exists()) {
   //...
} else {
    Log.d(TAG, "PDF not exists");
}
``

**Comment by MahmoudElmoghazy** [comment]
I have the same problem can u tell me the final answer ?!

**Comment by n0n1** [comment]
@MahmoudElmoghazy put your file (sample.pdf) on the SD card in application folder.

**Comment by MahmoudElmoghazy** [comment]
but the pdf file is local file i use it from my assets folder how can i get it from externalStorageDirectory ?!

**Comment by n0n1** [comment]
@MahmoudElmoghazy 
For example:
 - Searching directories
 - Initialize files
 - write to new file
````
var dir;
if(Ti.Filesystem.isExternalStoragePresent()) {
	dir = Ti.Filesystem.externalStorageDirectory;
} else {
	dir = Ti.Filesystem.applicationDataDirectory;	
}
var file = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "sample.pdf");
var dFile = Ti.Filesystem.getFile(dir, "sample.pdf");
if (file.exists() && (!destFile.exists())) {
	destFile.write(file.read());
}
````
