### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by MahmoudElmoghazy** [mano-mykingdom/titanium-mupdf#11]
Hi now i have a probelm now every time i run the application the application go crash and give me this bug
[ERROR] :  TiApplication: (main) [199,199] Sending event: exception on thread: main msg:java.lang.NullPointerException; Titanium 4.0.0,2015/05/18 15:42,9239ff9
[ERROR] :  TiApplication: java.lang.NullPointerException
[ERROR] :  TiApplication: 	at com.artifex.mupdflib.ReaderView.getOrCreateChild(ReaderView.java:843)
[ERROR] :  TiApplication: 	at com.artifex.mupdflib.ReaderView.onLayout(ReaderView.java:717)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:13754)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4362)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:13754)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4362)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:13754)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4362)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:13754)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4362)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:13754)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4362)
[ERROR] :  TiApplication: 	at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:13754)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4362)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:13754)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4362)
[ERROR] :  TiApplication: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
[ERROR] :  TiApplication: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
[ERROR] :  TiApplication: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:13754)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4362)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:13754)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4362)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
[ERROR] :  TiApplication: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doFrame(Choreographer.java:525)
[ERROR] :  TiApplication: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
[ERROR] :  TiApplication: 	at android.os.Handler.handleCallback(Handler.java:615)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:92)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:137)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:4745)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:511)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$Metho
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)

but i remove 
var pdfReader = READER_MODULE.createView( {
	file: file
} );
doesn't crash

**Comment by mano-mykingdom** [comment]
Guess your issue is same as #10, so closing this.
