### ISSUE TITLE
MuPDF as name of app

### ISSUE THREAD

**Issue by nonno** [mano-mykingdom/titanium-mupdf#13]
In each strings.xml you add:
<string name="app_name">MuPDF</string>

If for example I use this module in a application where I defined only file strings.xml for language "en", and device is configured in Italian, your app_name overwrite mine and as app name I see MuPDF instead of my app's name. Why you add app_name to strings.xml of a module? I'm not very expert in Titanium's modules so probably there is a reason you added this string in your strings.xml. Could I remove these app_name properties?

![screenshot_2015-10-22-12-33-16](https://cloud.githubusercontent.com/assets/4105325/10663421/8fe3adf0-78bb-11e5-96b7-eb9fbd6d5f5a.png)

**Comment by mano-mykingdom** [comment]
Yes, You can remove `app_name`.

I'm not so happy with MuPDF but I didn't have any other option, it was the only free version for android. There were no documentation too. May be updating this to the latest version [here](https://github.com/joniks/Android-MuPDF) will fix several issues.

**Comment by nonno** [comment]
Perfect, thank you Manoy. I'm going to fork the project and correcting it.

**Comment by mano-mykingdom** [comment]
:+1:

**Comment by MahmoudElmoghazy** [comment]
I have the same issus what should i do to end this problem ?!

**Comment by nonno** [comment]
@MahmoudElmoghazy in theory I solved it with this commit:
https://github.com/mano-mykingdom/titanium-mupdf/commit/7a4547010b418de76434f50355d290e7e00d685e
