### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by nonno** [mano-mykingdom/titanium-mupdf#14]
I've just updated your module in my project from the version 1.4 to the 1.8, now when I navigate through a pdf, sometimes, the app crashes with a OutOfMemoryError. I'm not using files so big, it happened also with a file of 12 pages without images.
I'm testing my app on a Samsung Galaxy Tab S2, with Android 5.0.2 and Titanium SDK 5.0.2.GA.

Is it normal to throw a similar Error if createCookie doesn't return anything?

[ERROR] AndroidRuntime: FATAL EXCEPTION: main
[ERROR] AndroidRuntime: Process: MY_APP_ID, PID: 6153
[ERROR] AndroidRuntime: java.lang.OutOfMemoryError
[ERROR] AndroidRuntime: 	at com.artifex.mupdflib.MuPDFCore$Cookie.<init>(MuPDFCore.java:88)
[ERROR] AndroidRuntime: 	at com.artifex.mupdflib.MuPDFCancellableTaskDefinition.<init>(MuPDFCancellableTaskDefinition.java:9)
[ERROR] AndroidRuntime: 	at com.artifex.mupdflib.MuPDFPageView$17.<init>(MuPDFPageView.java:609)
[ERROR] AndroidRuntime: 	at com.artifex.mupdflib.MuPDFPageView.getDrawPageTask(MuPDFPageView.java:609)
[ERROR] AndroidRuntime: 	at com.artifex.mupdflib.PageView.updateHq(PageView.java:657)
[ERROR] AndroidRuntime: 	at com.artifex.mupdflib.MuPDFReaderView.onSettle(MuPDFReaderView.java:268)
[ERROR] AndroidRuntime: 	at com.artifex.mupdflib.ReaderView$2.run(ReaderView.java:914)
[ERROR] AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
[ERROR] AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] AndroidRuntime: 	at android.os.Looper.loop(Looper.java:145)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6145)
[ERROR] AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by nonno** [comment]
In MuPDFCore I tried to replace
throw new OutOfMemoryError();
with
throw new RuntimeException("createCookie haven't returned anything");

Now app doesn't explode anymore, but I don't know what kind of collateral effects I could obtain...

**Comment by mano-mykingdom** [comment]
Out of memory very easily happens on Samsung devices did you try `largeHeap`?

**Comment by nonno** [comment]
From the beginning...
            <application android:debuggable="false"
                android:hardwareAccelerated="true"
                android:largeHeap="true" android:theme="@style/Theme.MyTheme">

The problem is that the OutOfMemory is only simulated with the throw. Do you agree if I replace it with a throw new RuntimeExcepion? An error is not catchable and cause a crash, with RuntimeException it seems to work.
