### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mpociot** [mano-mykingdom/titanium-mupdf#2]
Hi,

it seems like the module is leaking memory.

To reproduce this issue, simply open a PDF in a new window, close it and repeat this process multiple times.

```
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 89.768MB for 13598736-byte allocation
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 102.640MB for 13598736-byte allocation
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 115.625MB for 13598736-byte allocation
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 129.120MB for 13598736-byte allocation
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 142.009MB for 13598736-byte allocation
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 154.876MB for 13598736-byte allocation
```

Eventually the app will crash.

**Comment by mpociot** [comment]
Seems like this is an easy fix :)

http://stackoverflow.com/questions/10306569/outofmemory-in-mupdf

**Comment by mpociot** [comment]
It's me again.
I fixed the memory leak in my branch - you need to implement the "releaseViews" method on your ViewProxy.
My branch is currently not in a state where I could do a PR (since I needed to remove the search functionality in order to update muPDF).

You can take a look at the needed changes in my latest commit:

https://github.com/mpociot/titanium-mupdf/commit/48329694ba78bcb8d14a7af39a003f7c9981ff74

**Comment by mano-mykingdom** [comment]
Thanks @mpociot for your help. But MuPDF doesn't support a lot of functionalities that the modern pdf readers (like FoxIt) do. So I'm searching for a better open source library.
