### ISSUE TITLE
doInBackground() - java exception crashing the app.

### ISSUE THREAD

**Issue by gabeaguirre** [mano-mykingdom/titanium-mupdf#3]
Occasionally, when opening a PDF in the viewer the following exception crashes the application:

java.lang.RuntimeException: An error occured while executing doInBackground()

This seems to happen randomly and isn't very reproducible, however it obviously has something to do with threads.

**Comment by mpociot** [comment]
I think this has to do with #2 
Can you take a look at the HEAP size? It should constantly grow until the app crashes
