### ISSUE TITLE
Is there a reason this is 16MB?

### ISSUE THREAD

**Issue by gabeaguirre** [mano-mykingdom/titanium-mupdf#5]
I was about to deploy with your PDF reader, but it is singlehandedly raising my APK size by multiple MB's, and about 18MB is you count the three arch's it builds for. Actually, unpacked it is around 50MB. I don't think I will be using this module, it bloats you APK size by a ridiculous amount.

**Comment by mano-mykingdom** [comment]
Sorry for the delayed response. You may try to build separate APK for each architecture to reduce the size.
