### ISSUE TITLE
Compatibility with newer versions

### ISSUE THREAD

**Issue by rgeade** [mano-mykingdom/titanium-mupdf#8]
When I import this module (all compiled versions in DIST) into Ti, it only allows me to select the 1.0 or 1.1 versions in the TiApp.xml viewer.  If I force a newer version, it says the version is not compatible with my current Titanium SDK.  I am running 3.5.0, but I have tried others as well.

**Comment by mattlanham** [comment]
+1

**Comment by mano-mykingdom** [comment]
22fd938bbaa98ff2f80f1641371da5a0758ce414
